name: my_file
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  percent_indicator: ^4.2.2
  mime_type: ^1.0.0
  device_info_plus: ^3.2.4
  path: ^1.8.1
  path_provider: ^2.0.11
  fluttertoast: ^8.0.9
  permission_handler: ^10.0.0
  intl: ^0.17.0
  open_filex: ^3.4.0
  device_apps: ^2.2.0
  video_player: ^2.4.5
  isolate_handler: ^1.0.1
  platform: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/ic_launcher.png"
  min_sdk_android: 21